### PR TITLE
improve google home support

### PR DESCRIPTION
**Pull request by TA2k**

### CODE REVIEW

**Comment by Apollon77** [comment]
Could you add some details? A list of added/changed stuff? Also as History ;-)

**Comment by Apollon77** [comment]
And ideally also Update package.json, is-package and readme with new version and changelog ;-) then new version will be faster published to npm.

**Comment by TA2k** [comment]
Done

**Comment by Apollon77** [comment]
Thank you.

**Comment by Apollon77** [comment]
ok to merge ... or should we wait? :-)

**Pull request merged**
